# This workflow will upload a Python Package using Twine when a release is created
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
# Test this workflow with `make gact-release`

name: "pub"

on:
    workflow_dispatch: # Manually trigger the workflow from the Actions tab
    release:
        types: [published]
    # a release is created automatically after the tag is pushed
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+" # this excludes tags like v1.0.0-rc1 or v1.0.0-beta1

permissions:
    # 'read' to access the list of commits
    contents: read

env:
    python-version: "3.14"

jobs:
    pub-build:
        runs-on: ubuntu-latest
        steps:
            # https://github.com/actions/checkout
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install deps
              uses: ./.github/actions/install-deps
              with:
                  python-version: ${{ env.python-version }}
            - name: Build package
              run: uv build

            - name: Store artifact
              uses: actions/upload-artifact@main
              with:
                  name: dist
                  path: dist

    pub-pypi:
        runs-on: ubuntu-latest
        needs: pub-build
        environment: pypi
        permissions:
            # A 'write' permission is mandatory for trusted publishing
            id-token: write
        steps:
            - name: Download artifact
              uses: actions/download-artifact@main
              with:
                  name: dist
                  path: dist

            - name: Publish package
              # https://github.com/marketplace/actions/pypi-publish
              uses: pypa/gh-action-pypi-publish@release/v1
              # When not using a Trusted Publisher, you can use the following credentials:
              # with:
              #     # https://pypi.org/manage/account/#api-tokens
              #     user: __token__
              #     password: ${{ secrets.PYPI_API_TOKEN }}
